### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_variant_access'

### ISSUE THREAD

**Issue by geissonator** [openbmc/bios-settings-mgr#2]
After picking up commit b5984b87eb93f57f8bc2c123717527076a560753, our p10bmc system started seeing this error when starting:

```
Sep 14 13:30:34 p10bmc biosconfig-manager[309]: terminate called after throwing an instance of 'std::bad_variant_access'
Sep 14 13:30:34 p10bmc biosconfig-manager[309]:   what():  std::get: wrong index for variant
Sep 14 13:30:34 p10bmc systemd-coredump[743]: Process 309 (biosconfig-mana) of user 0 dumped core.
Sep 14 13:30:34 p10bmc systemd[1]: xyz.openbmc_project.biosconfig_manager.service: Main process exited, code=dumped, status=6/ABRT
Sep 14 13:30:34 p10bmc systemd[1]: xyz.openbmc_project.biosconfig_manager.service: Failed with result 'core-dump'.
Sep 14 13:30:36 p10bmc systemd[1]: xyz.openbmc_project.biosconfig_manager.service: Scheduled restart job, restart counter is at 1.
```

There definitely a good chance this new commit is catching an issue but the fact we're getting the unhandled exception via the std::get means we have no way to debug this other then putting some debug logs into the code and trying to recreate. Be ideal if it was caught and we logged a valid issue to the journal for easier debug.

FYI @arunlalkm-intel .

**Comment by arunlalkm-intel** [comment]
We can use std::get_if, like 
const int64_t* value = std::get_if<int64_t>(&std::get<1>(stringOptions))

and do a if condition like 
if(value)
{
 // use *value
}
else
{
//log 
}

**Comment by geissonator** [comment]
Yeah, that makes sense to me. Just something so we can easily see the invalid request. Thanks.

**Comment by williamspatrick** [comment]
Rather than hold a pointer, you can also use `std::holds_alternative` to check the type held by the variant.

**Comment by lxwinspur** [comment]
@geissonator 
Could you check this patch?
https://gerrit.openbmc-project.xyz/c/openbmc/bios-settings-mgr/+/49126
